### ISSUE TITLE
[FEATURE] Add support for Umami

### ISSUE THREAD

**Issue by aozaki-kuro** [sunt-programator/CodeIT#288]
## Describe the feature you want

Umami is a free self-hosted analytics as an alternative choice of Google Analytics and provides detailed info.

But unfortunately I don't know how to write Go 😞

I hope this could be added to the supported list.

## Useful reference

The script added into <head> looks like this 

```html
<script async defer data-website-id="xxxxxxxx" src="https://example.com/umami.js"></script>
```

For the `config.toml`
```toml
[params.analytics.umami]
      id = "" # data-website-id
      domain = "" # replace example.com
```
