### ISSUE TITLE
[BUG] Utterances comment not shown when use right side TOC

### ISSUE THREAD

**Issue by beihai0xff** [sunt-programator/CodeIT#374]
## Describe the bug

Utterances comment not not showing when use right side TOC, and the HTML content is 
```html
<div id="comments"><div id="utterances"></div>
    <noscript>
        Please enable JavaScript to view the comments powered by <a href="https://utteranc.es/">Utterances</a>.
    </noscript>
</div>
```
But if I use Static TOC, the utterances comment return to normal, like the page [wingsxdu.com/about](https://wingsxdu.com/about/)

## Expected behavior

I want to use the right side TOC and utterances comment can work well.

## Screenshots

![2022-01-08 18-07-20 的屏幕截图](https://user-images.githubusercontent.com/47047644/148640273-607dd623-1adf-43f0-8477-0e551e01ebf8.png)

## Build Environment

- OS: [macOS, Ubuntu]
- Theme version/commit [0.2.0]
- Hugo version [hugo v0.91.2-1798BD3F+extended linux/amd64 ]

## Preview Environment

- OS: [macOS, Ubuntu]
- Browser [Chrome]

## Additional Information

Configuration files

```toml
    [params.page.toc]
      # whether to enable the table of the contents
      enable = true
      # whether to keep the static table of the contents in front of the post
      keepStatic = false
      # whether to make the table of the contents in the sidebar automatically collapsed
      auto = true

    [params.page.comment]
      enable = true
      [params.page.comment.utterances]         # utteranc is a comment system based on GitHub issues. see https://utteranc.es
        enable = true
        repo = "beihai0xff/blog-comment"    # The repo to store comments
        issueTerm = "pathname"
        lightTheme = "github-light"
        darkTheme = "github-dark"
```
